### ISSUE TITLE
[Volunteer] Add doc and unit test for register-instance

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#2449]
### Volunteer help

Hi Community

We've added the ability to register instances of the gateway itself to the registry. 

can config this in shenyu-boostarp yaml.

```
shenyu:
  instance:
    enabled: false
    registerType: zookeeper #etcd #consul
    serverLists: localhost:2181 #http://localhost:2379 #localhost:8848
    props:
```

So there will be the following tasks：

- [x] new register instance doc to website
- [ ] add unit test for shenyu-register-instance-core
- [ ] add unit test for shenyu-register-instance-zookeeper
