### ISSUE TITLE
[Question] <title> Shenyu gateway HttpClient for connectionProvider of netty appears before response

### ISSUE THREAD

**Issue by como-ca** [apache/shenyu#2780]
### Question

Shenyu gateway  Use HttpClient for connectionProvider of netty appears  ” **Connection prematurely closed BEFORE response**  “ error .
My app runtime environment is configured as cpu  8 core , rom 8G , and 4 pod .
and this is my httpclient config （ netty & heepclient ）:
```
shenyu:
  httpclient:
    connectTimeout: 30000
    responseTimeout: 15000
    readTimeout: 30000
    writeTimeout: 30000
netty:
  tcp:
    select:
      count: 4
    worker:
      count: 8
```

Excuse me, how to solve this problem ?
