### ISSUE TITLE
[BUG] show login page?

### ISSUE THREAD

**Issue by qicz** [apache/shenyu#3145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when disabling the `oauth2` plugin, access the 915 show the login page.

```
shenyu:
   plugins:
      oauth2:
        enabled: false
```

![image](https://user-images.githubusercontent.com/2174082/160553461-c57dc9f7-0283-4c00-b5d9-8a023db9660d.png)

### Environment

```markdown
ShenYu version(s): last
```
