### ISSUE TITLE
with registertype=zookeeper, metadata doesnot clear when dubbo service is offline

### ISSUE THREAD

**Issue by hhfdna** [apache/shenyu#3243]
### Question

It's not graceful for backend service to config shenyu admin's address, especially username and passsword.
for example:
```yaml
shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://localhost:9095 #22.11.15.59:2181 #http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
```

so i prefer use zookeeper as registertype. It looks fine for dubbo invocation,but when dubbo service  gets offline, in admin dashboard, the selector and rule lists are still there, and so with zookeer path:
```bash
[zk: localhost:2181(CONNECTED) 113] ls /shenyu/register/metadata/dubbo/dubbo
[org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.findByListId, org.apache.shenyu.examples.dubbo.api.service.DubboTestService.findList, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.batchSaveAndNameAndId, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.batchSave, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.findByIdsAndName, org.apache.shenyu.examples.dubbo.api.service.DubboTestService.findById, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.findByStringArray, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.saveComplexBeanTestAndName, org.apache.shenyu.examples.dubbo.api.service.DubboTestService.insert, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.saveComplexBeanTest, org.apache.shenyu.examples.dubbo.api.service.DubboTestService.findAll, org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService.findByArrayIdsAndName]
``` 

It seems like this metadata should be removed when service instance  is offline. isnt it?
