### ISSUE TITLE
[Question] <title>mac m1 start application fail，websocket connection refused 

### ISSUE THREAD

**Issue by Cyoking** [apache/shenyu#3880]
### Question

The configuration of h2 is used, and other contents have not been changed.
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/41101749/186877884-cbae2196-29d8-4909-8392-438c31035ae5.png">

The error message after startup is as follows：
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/41101749/186878053-f692a79e-3e41-4b1f-9938-ab332c19d7a1.png">

**Comment by yu199195** [comment]
pls in english？

**Comment by Cyoking** [comment]
> 

👌

**Comment by Cyoking** [comment]
> pls in english？

can you see what's the problem?

**Comment by yu199195** [comment]
My guess  : your admin address is not accessible through localhost.  You can visit in your browser  : localhost:9095  ？.

if not, pls modify  `application.yaml` in  `shenyu-bootstrap` : 

```yaml
shenyu:
  sync:
    websocket:
      urls: ws://your ip:9095/websocket
      allowOrigin: ws://your ip:9195
```
