### ISSUE TITLE
[Question] <shenyu-boostrap  use  nacos sync failed>

### ISSUE THREAD

**Issue by niejian** [apache/shenyu#3886]
### Question

when I use nacos to sync data from `admin` to `bootstrap`. But when I start `bootstap`, in its log，doesn't show data sync from `admin`, switch to `websocket`, it shown。

* nacos config
```yaml
  sync:
#    websocket:
#      urls: ws://localhost:9095/websocket
#    zookeeper:
#      url: localhost:2181
#      sessionTimeout: 5000
#      connectionTimeout: 2000
#    http:
#      url: http://localhost:9095
#      username:
#      password:
    nacos:
      url: 192.168.240.132:8841
      namespace: public
      username: nacos
      password: nacos

```

* **use nacos to sync, `bootstrap` log show**
![image](https://user-images.githubusercontent.com/7080323/187133166-33c60597-5606-4dff-a85c-19b2476fece9.png)
* **use websocket to sync**
![image](https://user-images.githubusercontent.com/7080323/187133422-c9df5f2f-2ce5-4009-bd20-412332c9e28a.png)

any body konws why?
