### ISSUE TITLE
[BUG] doRegister Failed to execute,wait to retry.

### ISSUE THREAD

**Issue by xiaohei88** [apache/shenyu#4219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

shenyu-admin日志一直输出：2022-11-28 12:25:24.748 [TID: N/A] [APP:shenyu-admin] [xxx] [EXT:] [shenyu-shared_wheel_timer-3] WARN  org.apache.shenyu.common.timer.AbstractRetryTask:112 - Failed to execute task:/auth:divide,retried：51 ,total retries:-1,cause:doRegister Failed to execute,wait to retry.     

客户端http方式注册失败。
虽然客户端提示成功： o.a.s.register.client.http.utils.RegisterUtils:63 - uri client register success。但是在控制台查不到Selector

### Expected Behavior

客户端用http注册的方式成功即可。

### Steps To Reproduce

```yml
shenyu:
  register:
    registerType: http
    serverLists: http://localhost:9095
    props:
      username: admin
      password: 123456
  client:
    http:
      props:
        contextPath: ${server.servlet.context-path}
```
appName不配置即可

### Environment

```markdown
ShenYu version(s):2.5.0
```
