### ISSUE TITLE
[BUG] Metrics plugin missing in shenyu admin console

### ISSUE THREAD

**Issue by hemalatha2808** [apache/shenyu#4596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Description:**

Deployed apache shenyu using k8s deployment files and enabled "metrics" in the configmap of Shenyu admin. However, I don't see the metrics plugin available in the admin UI.

**Steps to Reproduce:**

1. As per this doc: https://shenyu.apache.org/docs/deployment/deployment-k8s, deployed shenyu-admin & shenyu-bootstrap pods
2. In the shenyu-admin configmap, enabled metrics and deployed the configmap

**Issues:**

1. Metrics plugin is not available under Plugins section. PFA
2. As per our requirement, we have to fetch the Response times of each API path/endpoint. Is there a metric available in shenyu to get the response times?

### Environment

```markdown
ShenYu version(s):2.5.1
```

### Anything else?

![metrics_plugin](https://user-images.githubusercontent.com/17244657/235118325-34f94c92-896a-47e5-9a0f-3449432571c4.PNG)

**Comment by yu199195** [comment]
Metrics plugin not in shenyu admin，

you can config metrics in application.yaml

```yaml
  metrics:
    enabled: true 
    name : prometheus
    host: 127.0.0.1
    port: 8090
    jmxConfig:
    props:
      jvm_enabled: true
```
