### ISSUE TITLE
[Question] <readAddress(..) failed: Connection reset by peer>

### ISSUE THREAD

**Issue by songchen2017** [apache/shenyu#4902]
### Question

各位老师好，我们是基于该开源项目二开的一个网关服务。
在测试环境以及预生产环境一切都很正常。
上线生产环境之后每天都有偶发的报错，部分异常信息如下：
readAddress(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

很明显是因为往已经断开的链接里写入数据导致的，但是我并不清楚到底是哪个链接被断开了。
网上查找资料，JVM加上-Dreactor.netty.pool.leasingStrategy=lifo 该配置效果也不明显。

由于我们系统刚上线，访问量并不高，平均高峰期qps也就十位数，所以应该也不是因为负载过高导致的断开旧链接。

有怀疑过是下游服务tomcat的maxKeepAliveRequests或者keepAliveTimeout等参数导致的，所以下游服务也做了一次修改，代码如下：.setMaxKeepAliveRequests(-1);
           .setKeepAliveTimeout(60000);

效果依然不明显，然后我们发现网关服务的http keepAlive根本没有开启，所以应该和下游服务器的tomcat无关才对。

网关服务配置如下：
```
      netty:
        http:
          webServerFactoryEnabled: true
          selectCount: 1
          workerCount: 8
          accessLog: false
          serverSocketChannel:
            soRcvBuf: 87380
            soBackLog: 1024
            soReuseAddr: true
            connectTimeoutMillis: 10000
            writeBufferHighWaterMark: 65536
            writeBufferLowWaterMark: 32768
            writeSpinCount: 16
            autoRead: false
            allocType: "pooled"
            messageSizeEstimator: 8
            singleEventExecutorPerGroup: true
          socketChannel:
            soKeepAlive: true
            soReuseAddr: true
            soLinger: -1
            tcpNoDelay: true
            soRcvBuf: 87380
            soSndBuf: 16384
            ipTos: 0
            allowHalfClosure: false
            connectTimeoutMillis: 10000
            writeBufferHighWaterMark: 65536
            writeBufferLowWaterMark: 32768
            writeSpinCount: 16
            autoRead: false
            allocType: "pooled"
            messageSizeEstimator: 8
            singleEventExecutorPerGroup: true
      httpclient:
        strategy: webClient
        connectTimeout: 3000
        responseTimeout: 3000
        readerIdleTime: 3000
        writerIdleTime: 3000
        allIdleTime: 3000
        readTimeout: 3000
        writeTimeout: 3000
        wiretap: false
        keepAlive: false
        pool:
          type: FIXED
          name: access-proxy
          maxConnections: 720
          acquireTimeout: 3000
          maxIdleTime: 3000
        threadPool:
          prefix: access-gateway
          selectCount: 1
          workerCount: 16
          daemon: true
```

尝试过调整maxIdleTime等参数，依然没有效果。

也试着调整过连接器，重点在.maxLifeTime(Duration.ofSeconds(60))和.evictInBackground(Duration.ofSeconds(120))
```
public static ConnectionProvider buildFixedConnectionPool(final String poolName, final Integer maxConnections,
                                             final Long acquireTimeout, final Duration maxIdleTime) {
        if (maxConnections <= 0) {
            throw new IllegalArgumentException("Max Connections value must be strictly positive");
        }
        if (acquireTimeout < 0) {
            throw new IllegalArgumentException("Acquire Timeout value must be positive");
        }
        return ConnectionProvider.builder(poolName)
                .maxConnections(maxConnections)
                .pendingAcquireTimeout(Duration.ofMillis(acquireTimeout))
                .maxIdleTime(maxIdleTime)
                .maxLifeTime(Duration.ofSeconds(60))
                .evictInBackground(Duration.ofSeconds(120))
                .build();
    }
```

机器规格：4c8g
JVM部分配置如下：
-Xms4096m -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/admin/var/logs/heapdump.%p.hprof -XX:MaxDirectMemorySize=2048m -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:+PrintGC -XX:MetaspaceSize=200m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC

JDK：OpenJDK Runtime Environment (build 1.8.0_222-b10)

请问还有什么办法可以尝试的吗？
