### ISSUE TITLE
[Question] Can I use RateLimiter with my Spring Cloud Gateway?

### ISSUE THREAD

**Issue by ysu6691** [apache/shenyu#5440]
### Question

I want to use ShenYu RateLimiter with my Spring Cloud Gateway.
I tried, but springCloud proxy wasn't applied.
Thank you for your reply.

```
// application.yml

server:
  port: 8000

spring:
  application:
    name: springCloudTest
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8083/
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://localhost:8084/
          predicates:
            - Path=/second-service/**

shenyu:
  register:
    registerType: http
    serverLists: http://localhost:9095
    props:
      username: admin
      password: 123456
  client:
    springCloud:
      props:
        contextPath: /spring
        addPrefixed: false
```

![image](https://github.com/apache/shenyu/assets/109272360/61095466-7016-4afd-bc1b-86a158bdc310)
