### ISSUE TITLE
[Question] Shenyu-admin dose not support nacos as a registerType on 2.6.1?

### ISSUE THREAD

**Issue by Frostlock-Z** [apache/shenyu#5441]
### Question

I tryed to use nacos as the shenyu-admin register.

The part of my application.yml is like below.

``` yaml
shenyu:
  register:
    registerType: nacos
```

After started the application, I got an "IllegalArgumentException: nacos name is error" exception.

This exception never appear on 2.6.0.

Dose the new verision stop supporting the nacos, or did I do something wrong?
