### ISSUE TITLE
[Question] How can I shield endless logs in console?

### ISSUE THREAD

**Issue by ColdFragrance** [apache/shenyu#5579]
### Question

Hi everyone:
I upgraded shenyu 2.6.1,but got endless logs in console as follows.How can I shield it?
![afd7804df2acfd618851e3be73045d6](https://github.com/apache/shenyu/assets/31916039/d2a37533-0810-42bb-9188-9c53e51e3625)

**Comment by ColdFragrance** [comment]
Nobody help me?

**Comment by yu199195** [comment]
can you config this in logback.xml
```yaml
logging:
  level:
    root: info
    org.apache.shenyu.lottery:  you level
    org.apache.shenyu: you level
```
