### ISSUE TITLE
[Question] How can we configure it to isolate requests from accessing these internal interfaces of shenyu-bootstrap?

### ISSUE THREAD

**Issue by chaclus** [apache/shenyu#5581]
### Question

As the entry point for traffic following load balancing, the Shenyu gateway directs all subdomains directly to shenyu-bootstrap. However, some API interfaces in shenyu-bootstrap are unauthenticated and can be accessed directly via domain + URI, such as /actuator, /actuator/env, etc. How can we configure it to isolate requests from accessing these internal interfaces of shenyu-bootstrap?

**Comment by hql0312** [comment]
in shenyu bootstrap , you can config the internal interface like this :
1.  you can write a api  start with  /shenyu , such as /shenyu/detail 
2. you can config health path in yaml , shenyu.health.paths
```yaml
shenyu: 
  health:
    enabled: true
    paths:
      - /actuator
      - /health_check
```
